import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })





export default function Home() {
// function handleSubmit(){return}


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          {/*<form onSubmit={handleSubmit}>*/}
          {/*    <input*/}
          {/*        name="email"*/}
          {/*        type="email"*/}
          {/*        placeholder="Enter email"*/}
          {/*        required*/}
          {/*    />*/}
          {/*    <textarea*/}
          {/*        name="message"*/}
          {/*        placeholder="Enter message"*/}
          {/*        required*/}
          {/*    />*/}
          {/*    <input*/}
          {/*        name="bot-field"*/}
          {/*        type="text"*/}
          {/*    />*/}
          {/*    <button type="submit">Send</button>*/}
          {/*</form>*/}
      </main>
    </>
  )
}
